## 02. numpy

### 2-1. numpy 배열 연산

In [10]:
import numpy as np

In [11]:
# 배열 간 연산 (1차원)
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

print(a1 + a2)
print(a1 - a2)

[5 7 9]
[-3 -3 -3]


In [12]:
# 배열 간 연산 (2차원)
a1 = np.arange(1, 5).reshape(2, 2)
a2 = np.arange(11, 15).reshape(2, 2)

print(a1, "\n")
print(a2, "\n")
print(a1 + a2, "\n")
print(a2 - a1, "\n")

[[1 2]
 [3 4]] 

[[11 12]
 [13 14]] 

[[12 14]
 [16 18]] 

[[10 10]
 [10 10]] 



In [13]:
# 배열과 스칼라 연산 (1차원)
a1 = np.array([1, 2, 3, 4])
print(a1 + 10, "\n")
print(a1 * 2)

[11 12 13 14] 

[2 4 6 8]


In [14]:
# 배열과 스칼라 연산 (2차원)
a1 = np.arange(1, 5).reshape(2, 2)
a2 = np.arange(11, 15).reshape(2, 2)
print(a1, "\n")
print(a2, "\n")
print(a1 + 5, "\n")
print(a2 * 3, "\n")
print(a2 / 2, "\n")

[[1 2]
 [3 4]] 

[[11 12]
 [13 14]] 

[[6 7]
 [8 9]] 

[[33 36]
 [39 42]] 

[[5.5 6. ]
 [6.5 7. ]] 



In [15]:
# 배열의 구조가 다를 경우
a1 = np.array([1, 2])
a2 = np.array([1, 2, 3])
# print(a1 + a2)  > ValueError

# 브로드캐스팅
# 자동으로 배열의 크기를 확장 -> 서로 다른 크기의 배열 간 연산을 가능하게 하는 기능
# 1. 두 배열의 차원을 뒤(낮은 차원)에서부터 비교
# 2. 크기가 같거나
# 3. 한쪽이 1인 경우 확장이 가능

a1 = np.array([[1, 2, 3],
               [4, 5, 6]]) # (2,3)
a2 = np.array([10, 20, 30]) # 길이가 3인 1차원 배열 (3,)

# 1차원 길이 3
[10,20,30]

# 2차원으로 변형 (1,3)
[[10,20,30]]

# 2차원의 행이 2 -> 2로 확장
[[10,20,30],
 [10,20,30]]

print(a1 + a2)

[[11 22 33]
 [14 25 36]]


In [16]:
# 브로드 캐스팅 예제
a1 = np.array([[1], [2], [3]]) # (3,1)
a2 = np.array([10, 20, 30]) # (3,)

# a2: (3,) > (1, 3) 변형
[[10, 20, 30]]

# a1과 a2 비교 > (3, 1), (1, 3)
[[1, 1, 1], [2, 2, 2], [3, 3, 3]]
[[10, 20, 30], [10, 20, 30], [10, 20, 30]]

print(a1 + a2)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [26]:
# 1. 다음 배열을 생성하고, 모든 요소에 3을 더하세요.
arr1 = np.array([1, 2, 3, 4])
print(f"문제1:\n{arr1 + 3}\n")

# 2. 아래 2차원 배열에서 각 요소를 -1로 곱한 새로운 배열을 만드세요.
arr2 = np.array([[5, 10],
               [15, 20]])
print(f"문제2:\n{arr2 * -1}\n")

# 3. 아래 두 배열의 요소별 곱셈과 나눗셈 결과를 각각 출력하세요.
arr3_1 = np.array([2, 4, 6])
arr3_2 = np.array([1, 2, 3])
print(f"문제3-1:\n{arr3_1 * arr3_2}\n")
print(f"문제3-2:\n{arr3_1 / arr3_2}\n")

문제1:
[4 5 6 7]

문제2:
[[ -5 -10]
 [-15 -20]]

문제3-1:
[ 2  8 18]

문제3-2:
[2. 2. 2.]



In [22]:
# 4. 아래 배열에서 모든 요소를 최대값 100으로 만들기 위해 필요한 값을 더한 결과 배열을 브로드 캐스팅으로 만드세요.
arr4 = np.array([[95, 97],
                 [80, 85]])
result = 100 - arr4
print(f"문제4:\n{result}\n")

# 5. 아래 2차원 배열에서 각 행에 다른 값을 곱하여 새로운 배열을 만드세요,
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
arr5_1 = np.array([[10],
                   [100]])
print(f"문제5:\n{arr5 * arr5_1}\n")

문제4:
[[ 5  3]
 [20 15]]

문제5:
[[ 10  20  30]
 [400 500 600]]



In [25]:
# 6. 아래 배열에서 각 행마다 다른 스칼라 값을 더하기 위해
# 1차원 배열을 만들어 브로드 캐스팅 연산을 수행하세요,
# 첫 번째행에 100, 두 번째 행에 200, 세 번째 행에 300 더하세요.
arr6 = np.array([[10, 20],
                 [30, 40],
                 [50, 60]])

arr6_1 = np.array([[100],
                   [200],
                   [300]])

print(f"문제6:\n{arr6 + arr6_1}\n")

문제6:
[[110 120]
 [230 240]
 [350 360]]



### 2-2. 통계 함수 및 집계 연산

In [33]:
a = np.array([[1, 2, 3],[4, 5, 6]])

print(f"1. 원소의 합: {np.sum(a)}")
print(f"2. 원소의 평균: {np.mean(a)}")
print(f"3. 표준편차: {np.std(a)}")
print(f"4. 최대값: {np.max(a)}")
print(f"5. 최소값: {np.min(a)}")
print(f"6. 최대값의 인덱스: {np.argmax(a)}")
print(f"7. 최소값의 인덱스: {np.argmin(a)}")

1. 원소의 합: 21
2. 원소의 평균: 3.5
3. 표준편차: 1.707825127659933
4. 최대값: 6
5. 최소값: 1
6. 최대값의 인덱스: 5
7. 최소값의 인덱스: 0


In [66]:
# 축(axis) 단위 연산
# axis = 0 > 가장 높은 차원 기준 > 행 기준
# 행 기준 = 행을 따라 연산 = 행을 증가시키며 연산

# axis = 1 > 그 다음 차원 기준 > 열 기준
# 열 기준 = 열을 따라 연산 = 열을 증가시키며 연산

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(f"열 기준 합: {np.sum(a, axis = 0)}")
print(f"행 기준 합: {np.sum(a, axis = 1)}\n")

print(f"열 기준 평균: {np.mean(a, axis = 0)}")
print(f"행 기준 평균: {np.mean(a, axis = 1)}")

열 기준 합: [12 15 18]
행 기준 합: [ 6 15 24]

열 기준 평균: [4. 5. 6.]
행 기준 평균: [2. 5. 8.]


In [67]:
# 누적 연산
arr = np.array([1, 2, 3, 4])

print(f"누적합: {np.cumsum(arr)}")
print(f"누적곱: {np.cumprod(arr)}")

누적합: [ 1  3  6 10]
누적곱: [ 1  2  6 24]


In [68]:
# 실습 2

# 1. 아래 배열의 전체 합계와 평균을 각각 구하세요.
arr1 = np.array([5, 10, 15, 20])
print(f"문제1:\n 합계: {np.sum(arr1)}")
print(f" 평균: {np.mean(arr1)}\n")

# 2. 다음 2차원 배열에서 전체 최소값과 최대값을 구하세요.
arr2 = np.array([[3, 7, 1],
               [9, 2, 8]])
print(f"문제2:\n 최소값: {np.min(arr2)}")
print(f" 최대값: {np.max(arr2)}\n")

# 3. 아래 배열에서 각 열의 합계와 각 행의 합계를 각각 구하세요.
arr3 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(f"문제3:\n 열 기준 합: {np.sum(arr3, axis = 0)}")
print(f" 행 기준 합: {np.sum(arr3, axis = 1)}")

문제1:
 합계: 50
 평균: 12.5

문제2:
 최소값: 1
 최대값: 9

문제3:
 열 기준 합: [12 15 18]
 행 기준 합: [ 6 15 24]


In [69]:
# 4. 아래 배열에서 행별 평균과 열별 평균을 각각 구하세요.
arr4 = np.array([[10, 20],
                 [30, 40],
                 [50, 60]])
print(f"문제4:\n 열 기준 평균: {np.mean(arr4, axis = 0)}")
print(f" 행 기준 평균: {np.mean(arr4, axis = 1)}\n")

# 5. 1차원 배열에서 전체 표준편차를 구하고, 각 요소가 평균으로부터 얼마나 떨어져 있는지 편차 배열을 만드세요. (값 -평균)
arr5 = np.array([2, 4, 4, 4, 5, 5, 7, 9])
arr5_std = np.std(arr5)
arr5_mean = np.mean(arr5)
print(f"문제5:\n 표준편차: {arr5_std}")
print(f" 평균: {arr5_mean}")
print(f" 편차배열: {arr5 - arr5_mean}\n")

# 6. 아래 2차원 배열에서 행 단위 누적 합과 열 단위 누적 곱을 각각 구하세요.
arr6 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(f"문제6:\n 누적합(열):\n {np.cumsum(arr6, axis = 0)}\n")
print(f" 누적합(행):\n {np.cumsum(arr6, axis = 1)}\n")
print(f" 누적곱(열):\n {np.cumprod(arr6, axis = 0)}\n")
print(f" 누적곱(행):\n {np.cumprod(arr6, axis = 1)}")

문제4:
 열 기준 평균: [30. 40.]
 행 기준 평균: [15. 35. 55.]

문제5:
 표준편차: 2.0
 평균: 5.0
 편차배열: [-3. -1. -1. -1.  0.  0.  2.  4.]

문제6:
 누적합(열):
 [[1 2 3]
 [5 7 9]]

 누적합(행):
 [[ 1  3  6]
 [ 4  9 15]]

 누적곱(열):
 [[ 1  2  3]
 [ 4 10 18]]

 누적곱(행):
 [[  1   2   6]
 [  4  20 120]]


### 2-3. 논리 연산과 조건 연산

In [55]:
# np.where() > 조건 기반 선택 함수
arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr > 30, "High", "Low")
print(result, "\n")

# 조건만 넣을 경우 조건을 만족하는 원소의 인덱스를 반환
arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr > 30)
print(result, "\n")
print(arr[result])

['Low' 'Low' 'Low' 'High' 'High'] 

(array([3, 4]),) 

[40 50]


In [62]:
# 논리 연산
    # and: & - 모든 조건이 True 여야 True
    # or: | - 조건 중 하나라도 True 면 True
    # not: ~ - True > False , False > True

# and 연산
arr = np.array([10, 20, 30, 40, 50])
mask = (arr > 10) & (arr < 50)
print(mask, "\n")
print(f"&연산: {arr[mask]}")

# or 연산
mask_or = (arr < 20)|(arr > 40)
print(f"|연산: {arr[mask_or]}")

# not 연산
mask_not = ~(arr > 30)
print(f"~연산: {arr[mask_not]}")

[False  True  True  True False] 

&연산: [20 30 40]
|연산: [10 50]
~연산: [10 20 30]


In [80]:
# 실습3. 
# 1. 1차원 배열 [5, 12, 18, 7, 30, 25]에서 10보다 크고 20보다 작은 값만 필터링하세요.
arr1 = np.array([5, 12, 18, 7, 30, 25])
arr1_mask = (arr1 > 10) & (arr1 < 20)
print(f"문제1:\n {arr1[arr1_mask]}\n")

# 2. 배열 [10, 15, 20, 25, 30, 35]에서 15 이하이거나 30 이상인 값만 선택하세요.
arr2 = np.array([10, 15, 20, 25, 30, 35])
arr2_mask = (arr2 <= 15)|(arr2 >= 30)
print(f"문제2:\n {arr2[arr2_mask]}\n")

# 3. 배열 [3, 8, 15, 6, 2, 20]에서 10 이상인 값을 모두 0으로 변경하세요.
arr3 = np.array([3, 8, 15, 6, 2, 20])
arr3_where = np.where(arr3 >= 10, 0, arr3)
print(f"문제3:\n {arr3_where}\n")

# 4. 배열 [7, 14, 21, 28, 35]에서 20 이상인 값은 "High", 나머지는 "Low"로 표시하는 새로운 배열을 생성하세요.
arr4 = np.array([7, 14, 21, 28, 35])
arr4_where = np.where(arr4 >= 20, "High", "Low")
print(f"문제4:\n {arr4_where}\n")

문제1:
 [12 18]

문제2:
 [10 15 30 35]

문제3:
 [3 8 0 6 2 0]

문제4:
 ['Low' 'Low' 'High' 'High' 'High']



In [92]:
# 5. 0 ~ 9 범위의 배열에서 짝수는 그대로 두고, 홀수는 홀수 값 × 10 으로 변환한 배열을 만드세요.
arr5 = np.arange(0, 10)
arr5_where = np.where(arr5 % 2 != 0 , arr5 * 10, arr5)
print(f"문제5:\n {arr5_where}\n")

# 6. 아래 2차원 배열에서 20 이상 40 이하인 값만 선택하세요.
arr6 = np.array([[10, 25, 30],
                 [40, 5, 15],
                 [20, 35, 50]])
arr6_mask = (20 <= arr6) & (arr6 <= 40)
print(f"문제6:\n {arr6[arr6_mask]}\n")

# 7. 배열 [1, 2, 3, 4, 5, 6] 에서 3의 배수가 아닌 값만 선택하세요.
arr7 = np.array([1, 2, 3, 4, 5, 6])
arr7_mask = (arr7 % 3 != 0)
print(f"문제7:\n {arr7[arr7_mask]}\n")


문제5:
 [ 0 10  2 30  4 50  6 70  8 90]

문제6:
 [25 30 40 20 35]

문제7:
 [1 2 4 5]



In [91]:
# 8. 랜덤 정수(0 ~ 100) 10개 배열에서 아래와 같이 새로운 배열을 만드세요.
    # 50 이상인 값은 그대로
    # 50 미만의 같은 50으로 변경
arr8 = np.random.randint(0, 101, (10, 10))
arr8_where = np.where(arr8 < 50, 50, arr8)
print(f"문제8:\n {arr8_where}\n")

# 9. 2차원 배열에서 아래와 같이 분류된 문자열 배열을 생성하세요.
    # 70이상 A
    # 30이상 70미만 B
    # 30미만 C
arr9 = np.array([[5, 50, 95],
                 [20, 75, 10],
                 [60, 30, 85]])
arr9_where = np.where(arr9 >= 70, "A", np.where(arr9 < 30, "C", "B"))
print(f"문제9:\n {arr9_where}")

문제8:
 [[50 50 89 54 82 50 50 50 50 87]
 [50 50 50 64 50 63 63 50 50 50]
 [50 50 50 60 77 60 50 50 95 50]
 [60 50 81 55 50 66 50 50 50 50]
 [50 85 50 82 50 92 87 54 87 50]
 [50 50 50 50 50 95 79 50 60 78]
 [50 98 54 50 88 50 64 50 98 74]
 [50 50 65 57 50 77 91 58 87 50]
 [73 50 71 50 50 50 50 50 63 79]
 [50 50 50 80 50 50 50 89 50 55]]

문제9:
 [['C' 'B' 'A']
 ['C' 'A' 'C']
 ['B' 'B' 'A']]


### 2-4. 행렬 곱셈
    - 두 행렬을 곱해서 새로운 행렬을 생성하는 연산
    - 첫 번째 행렬의 열수와 두 번째 행렬의 행수가 같아야 곱셈이 가능함.
    - np.dot(), np.matmul() -> 사용 

In [ ]:
# np.dot(a, b): 배열의 내적 연산
# 스칼라연산
a = np.array(3)
b = np.array(4)
print(np.dot(a, b),"\n")

# 1차원 배열 간 연산 -> 내적
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b), "\n") # 1*4 + 2*5 + 3*6

# 물건 구매
# 데이터 분석에서 벡터랑 배열
c = [1000, 2000, 5000, 10000]
d = [10, 3, 5, 7]
print(np.dot(c, d), "\n")

12 

32 

111000


In [97]:
# 2차원 배열간 연산 -> 행렬 곱셈
a = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
b = np.array([[1, 2], [3, 4], [5, 6]]) # (3, 2)
print(np.dot(a, b))

[[22 28]
 [49 64]]


In [ ]:
# np.matmul(a, b)
# Matrix Multiplication
# 스칼라 연산 시도시 에러

In [98]:
# 1차원 배열 간 연산 -> 내적
a = np.array([1, 2])
b = np.array([3, 4])
print(np.matmul(a, b))

11


In [99]:
# 2차원 배열간 연산 -> 행렬 곱셈
a = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
b = np.array([[1, 2], [3, 4], [5, 6]]) # (3, 2)
print(np.matmul(a, b))

[[22 28]
 [49 64]]


In [104]:
# 2차원 * 1차원간 연산
c = np.array([[1, 2], 
              [3, 4]]) #(2, 2)
d = np.array([5, 6]) #(2,)
print(np.matmul(c, d), "\n")
print(np.matmul(d, c), "\n")

# @ 연산자
e = np.array([[1, 2, 3]])
f = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(np.matmul(e, f), "\n")
print(e @ f)

[17 39] 

[23 34] 

[[22 28]] 

[[22 28]]


In [ ]:
# 실습4
# 1. 1부터 9까지의 정수로 채워진 (3, 3) 배열 A와, 모두 2로 채워진 (3, 2) 배열 B를 만들고 곱하세요.
arr1_A = np.arange(1, 10).reshape(3, 3)
print(arr1_A, "\n")
arr1_B = np.full((3, 2), 2)
print(arr1_B, "\n")
arr1 = np.dot(arr1_A, arr1_B)
print(f"문제1:\n {arr1}\n")

# 2.  4×4 단위행렬 I와, 4×4 난수 행렬 M(0~9 사이 정수) 간의 곱을 구하고, 결과와 M이 동일한 지 확인하세요.
arr2_I = np.eye(4, 4)
print(arr2_I, "\n")
arr2_M = np.random.randint(0, 10, (4, 4))
print(arr2_M, "\n")
arr2 = np.dot(arr2_I, arr2_M)
print(f"문제2:\n {arr2}\n") # 동일하다.

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2 2]
 [2 2]
 [2 2]] 

문제1:
 [[12 12]
 [30 30]
 [48 48]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[8 8 6 3]
 [7 6 5 1]
 [6 6 4 2]
 [5 5 9 4]] 

문제2:
 [[8. 8. 6. 3.]
 [7. 6. 5. 1.]
 [6. 6. 4. 2.]
 [5. 5. 9. 4.]]



In [114]:
# 3. 모든 값이 1인 (2, 5) 배열 X와, 5부터 14까지의 연속된 정수로 채워진 (5, 2) 배열 Y를 만들어 곱하세요.
arr3_X = np.full((2, 5), 1)
print(arr3_X, "\n")
arr3_Y = np.arange(5, 15).reshape(5, 2)
print(arr3_Y, "\n")
arr3 = np.dot(arr3_X, arr3_Y)
print(f"문제3:\n {arr3}\n")

# 4. 0 이상 5 미만의 임의의 정수로 채워진 (3, 2) 배열 C와 (2, 3) 배열 D를 각각 만들어 곱한 결과의 shape와 값을 출력하세요.
arr4_C = np.random.randint(0, 5, (3, 2))
print(arr4_C, "\n")
arr4_D = np.random.randint(0, 5, (2, 3))
print(arr4_D, "\n")
arr4 = np.dot(arr4_C, arr4_D)
print(f"문제4:\n {arr4}")

[[1 1 1 1 1]
 [1 1 1 1 1]] 

[[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]] 

문제3:
 [[45 50]
 [45 50]]

[[1 1]
 [3 4]
 [0 2]] 

[[1 4 4]
 [1 3 0]] 

문제4:
 [[ 2  7  4]
 [ 7 24 12]
 [ 2  6  0]]


In [121]:
# 문제1) 
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 2],
              [1, 0]])

arr1 = A @ B
print(f"문제1:\n {arr1}\n")

# 문제2)
v1 = np.array([[3, 1, 2]])
v2 = np.array([[4],
               [1],
               [5]])
arr2 = v1 @ v2
print(f"문제2:\n {arr2}\n")

# 문제3) 
A = np.array([[1, 2, 3],
              [4, 5, 6]])
arr3_1 = A * 2
print(arr3_1, "\n")

# arr3_2 = A @ A > ValueError

# 문제5)
A = np.array([11, 25, 30, 45, 60])
B = np.array([0.1, 0.2, 0.3, 0.2, 0.2])
arr5 = A @ B
print(f"문제5:\n {arr5}\n")


문제1:
 [[ 7  2]
 [19  6]]

문제2:
 [[23]]

[[ 2  4  6]
 [ 8 10 12]] 

문제5:
 36.1



In [128]:
A = np.array([[10, 20, 30],
              [5, 15, 25]])

B = np.array([0.2, 0.3, 0.5])

C = A @ B
print(C)

[23. 18.]
