## 03. NumPy
### 3-1. 배열의 형태 변형과 자원 확장 / 축소

In [2]:
import numpy as np

In [3]:
# array.ravel()
    # 다차원 배열을 1차원 배열로 펼침
    # 결과를 view로 반환 (view 변경 시 원본도 변경)
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a, "\n")

flat = a.ravel()
print(flat, "\n")

flat[2] = 100
print(flat, "\n")
print(a, "\n")

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6] 

[  1   2 100   4   5   6] 

[[  1   2 100]
 [  4   5   6]] 



In [4]:
# array.flatten()
    # 다차원 배열을 1차원 배열로 펼침
    # 결과를 복사본으로 반환 (복사는 변경 시 원본은 변경되지 않음)
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a, "\n")

flat = a.flatten()
print(flat, "\n")
flat[4] = 0
print(flat, "\n")
print(a, "\n")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

[1 2 3 4 5 6 7 8] 

[1 2 3 4 0 6 7 8] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 



In [6]:
# np.expand_dims(a, axis)
    # 저장한 위치에 차원 추가 (차원 확장)
    # 추가되는 자원은 1
a = np.array([[1, 2, 3], [4, 5, 6]])
print(f"원본:\n {a}, \n shape: {a.shape}\n")

# axis = 0
a0 = np.expand_dims(a, axis=0)
print(f"a0:\n {a0}, \n shape: {a0.shape}\n")

# axis = 1
a1 = np.expand_dims(a, axis=1)
print(f"a1:\n {a1}, \n shape: {a1.shape}\n")

# axis = 2
a2 = np.expand_dims(a, axis=2)
print(f"a2:\n {a2}, \n shape: {a2.shape}\n")

원본:
 [[1 2 3]
 [4 5 6]], 
 shape: (2, 3)

a0:
 [[[1 2 3]
  [4 5 6]]], 
 shape: (1, 2, 3)

a1:
 [[[1 2 3]]

 [[4 5 6]]], 
 shape: (2, 1, 3)

a2:
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]], 
 shape: (2, 3, 1)



In [11]:
# np.squeeze(a, axis)
    # 배열에서 크기가 1인 차원을 제거해주는 함수(자원 축소)
a = np.array([[[[1], [2], [3]]], [[[1], [2], [3]]]])
print(f"a:\n {a}, \n shape: {a.shape}\n") # (2, 1, 3, 1)

a1 = np.squeeze(a)
print(f"a1:\n {a1}, \n shape: {a1.shape}\n")

a:
 [[[[1]
   [2]
   [3]]]


 [[[1]
   [2]
   [3]]]], 
 shape: (2, 1, 3, 1)

a1:
 [[1 2 3]
 [1 2 3]], 
 shape: (2, 3)



In [13]:
# axis 지정하는 경우
a2 = np.zeros((1,4,1,2)) # (1, 4, 1, 2)
print(f"a2:\n {a2}, \n shape: {a2.shape}\n")

s1 = np.squeeze(a2, axis=0) # (4, 1, 2)
print(f"s1:\n {s1}, \n shape: {s1.shape}\n")

s2 = np.squeeze(a2, axis=2) # (1, 4, 2)
print(f"s2:\n {s2}, \n shape: {s2.shape}\n")

# 차원의 크기가 1이 아닌 차원은 제거할 수 X
# s3 = np.squeeze(a2, axis=1) > ValueError

a2:
 [[[[0. 0.]]

  [[0. 0.]]

  [[0. 0.]]

  [[0. 0.]]]], 
 shape: (1, 4, 1, 2)

s1:
 [[[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]], 
 shape: (4, 1, 2)

s2:
 [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]], 
 shape: (1, 4, 2)



In [10]:
# np.unique()
    # 배열에서 중복된 요소를 제거
a = np.array([1, 1, 1, 5, 5, 2, 2, 2, 2, 4, 4, 4, 3, 3, 3])
u1 = np.unique(a) # 고유값의 오름차순 배열 반환
print(u1)

u2, idx, inv, cnt = np.unique(a, return_index=True, return_inverse=True, return_counts=True)
print("인덱스:", idx)
print("원본의 고유값 인덱스:", inv)
print("값의 등장횟수", cnt)

[1 2 3 4 5]
인덱스: [ 0  5 12  9  3]
원본의 고유값 인덱스: [0 0 0 4 4 1 1 1 1 3 3 3 2 2 2]
값의 등장횟수 [3 4 3 3 2]


In [76]:
# 실습1

# 1. 아래의 배열을 사용해서
    # arr= np.array([[10, 20], [30, 40], [50, 60]])
    # 1) ravel과 flatten을 각각 사용해 1차원 배열로 변환하고,
    # 2) arr의 첫 번째 원소(arr[0,0])를 999로 바꾼 뒤 ravel 결과와 flatten 결과에 어떤 변화가 있는지 확인하세요.

arr1_1 = np.array([[10, 20], [30, 40], [50, 60]])
arr1_2 = arr1_1.ravel()
arr1_1[0, 0] = 999
print(f"원본:\n {arr1_1} \nravel:\n {arr1_2}\n") 

arr1_3 = np.array([[10, 20], [30, 40], [50, 60]])
arr1_4 = arr1_3.flatten()
arr1_3[0, 0] = 999
print(f"원본:\n {arr1_3} \nflatten:\n {arr1_4}\n")

원본:
 [[999  20]
 [ 30  40]
 [ 50  60]] 
ravel:
 [999  20  30  40  50  60]

원본:
 [[999  20]
 [ 30  40]
 [ 50  60]] 
flatten:
 [10 20 30 40 50 60]



In [82]:
# 2. 크기가 32x32인 이미지 데이터를 가정하고, 이 배열에 대해 expand_dims를 사용하여 shape (1, 32, 32)로 바꾸는 코드를 작성하세요.
arr2 = np.random.rand(32, 32)
arr2_1 = np.expand_dims(arr2, axis=0)
print(f"shape:\n {arr2_1.shape}\n")

shape:
 (1, 32, 32)



In [77]:
# 3. 아래 배열에서 불필요한 1차원을 모두 제거하여 shape이 (28, 28)이 되도록 만드세요.
arr3 = np.random.randint(0, 255, (1, 28, 28, 1))
arr3_1 = np.squeeze(arr3)
print(f"shape:\n {arr3_1.shape}\n")

shape:
 (28, 28)



In [78]:
# 4. 아래 2차원 배열을 1) 1차원 배열로 만든 후 2) 중복값을 제거한 뒤 shape (1, n)으로 재구성하세요.
arr4 = np.array([[3, 1, 2, 2],
                 [1, 2, 3, 1],
                 [2, 2, 1, 4]])
arr4_1 = arr4.flatten()
arr4_2 = np.unique(arr4_1)
arr4_3 = np.expand_dims(arr4_2, axis=0)
print(f"배열:\n {arr4_3} \nshape:\n {arr4_3.shape}\n")

배열:
 [[1 2 3 4]] 
shape:
 (1, 4)



In [95]:
# 5. 다음 배열을 shape (10,)로 만든 뒤 고유값배열을 구하세요.
arr5 = np.array([[[1], [3], [2], [1], [3], [2], [3], [1], [2], [3]]])

# (10,)으로 만들기
arr5_1 = np.squeeze(arr5)
print(f"배열:\n {arr5_1} \nshape:\n {arr5_1.shape}\n")

# 고유값 배열 구하기
arr5_2 = np.unique(arr5_1)
print(f"고유값 배열:\n {arr5_2}")


배열:
 [1 3 2 1 3 2 3 1 2 3] 
shape:
 (10,)

고유값 배열:
 [1 2 3]


In [93]:
# 6. 다음 배열을 1차원 배열로 만든 후 고유값만 추출해서 shape (고유값 개수, 1)인 2차원 배열로 변환하세요.
arr6 = np.array([[[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]],[[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]]])
arr6_1 = arr6.flatten()
arr6_2 = np.unique(arr6_1)
arr6_3 = np.expand_dims(arr6_2, axis=1)
print(f"배열:\n {arr6_3} \nshape:\n {arr6_3.shape}\n")

배열:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] 
shape:
 (9, 1)



### 3-2. 배열의 결합과 분리

In [ ]:
# np.concatenate(): 배열 시퀀스를 결합, 기존 구조 안에서 결합
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

result1 = np.concatenate((a, b), axis = 0) # 행 기준으로 결합
print(f"배열:\n {result1} \nshape:\n {result1.shape}\n")

# 결합이 불가 > 결합하는 axis를 제외한 나머지 차원이 같아야 함
# result2 = np.concatenate((a, b), axis = 1) > ValueError

c = np.array([[7], [8], [9]])
result3 = np.concatenate((result1, c), axis = 1) # 열 기준으로 결합
print(f"배열:\n {result3} \nshape:\n {result3.shape}\n")

배열:
 [[1 2]
 [3 4]
 [5 6]] 
shape:
 (3, 2)

배열:
 [[1 2 7]
 [3 4 8]
 [5 6 9]] 
shape:
 (3, 3)



In [102]:
# np.stack(): 새로운 차원을 추가하면서 결합
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# axis = 0
s1 = np.stack((a, b), axis = 0)
print(f"배열:\n {s1} \nshape:\n {s1.shape}\n")

# axis = 1
s2 = np.stack((a, b), axis = 1)
print(f"배열:\n {s2} \nshape:\n {s2.shape}\n")

배열:
 [[1 2 3]
 [4 5 6]] 
shape:
 (2, 3)

배열:
 [[1 4]
 [2 5]
 [3 6]] 
shape:
 (3, 2)



In [103]:
# hstack(): 열 방향(가로)으로 결합
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

h = np.hstack((a, b))
print(f"배열:\n {h} \nshape:\n {h.shape}\n")

# vstack(): 행 방향(세로)으로 결합
v = np.vstack((a, b))
print(f"배열:\n {v} \nshape:\n {v.shape}\n")

배열:
 [1 2 3 4 5 6] 
shape:
 (6,)

배열:
 [[1 2 3]
 [4 5 6]] 
shape:
 (2, 3)



In [109]:
# np.split(): 배열을 여러 개의 하위 배열로 분할
a = np.arange(9)
print(f"배열:\n {a} \nshape:\n {a.shape}\n")

s = np.split(a, 3)
print(f"배열:\n {s}")

print(f"배열:\n {s[0]}")
print(f"배열:\n {s[1]}")
print(f"배열:\n {s[2]}")

# 같은 크기로만 나눌 수 있음
# s = np.split(a, 4) > ValueError


배열:
 [0 1 2 3 4 5 6 7 8] 
shape:
 (9,)

배열:
 [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
배열:
 [0 1 2]
배열:
 [3 4 5]
배열:
 [6 7 8]


In [114]:
a = np.arange(16).reshape(4, 4)
print(f"배열:\n {a}\n")

s = np.split(a, [1, 3])
print(f"배열:\n {s}\n")
for part in s:
    print(part)

배열:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

배열:
 [array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [ ]:
# 실습2

# 1. 다음 두 배열을 행 방향으로 이어붙이세요.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
arr1 = np.concatenate((a, b), axis = 0) # 행 기준으로 결합
print(f"배열:\n {arr1} \nshape:\n {arr1.shape}\n")

# 2. 아래 배열을 3개로 같은 크기로 분할하세요.
a = np.arange(12)
arr2 = np.split(a, 3)
print(f"배열:\n {arr2}\n")

# 3. 다음 배열들을 새로운 축에 쌓아 shape가 (3, 2)인 배열을 만드세요.
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
arr3 = np.stack((a, b, c))
print(f"배열:\n {arr3} \nshape:\n {arr3.shape}\n")

배열:
 [[1 2]
 [3 4]
 [5 6]] 
shape:
 (3, 2)

배열:
 [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

배열:
 [[1 2]
 [3 4]
 [5 6]] 
shape:
 (3, 2)



In [154]:
# 4. shape가 (2, 3)인 아래 두 배열을 shape (2, 2, 3)인 3차원 배열을 만드세요.
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
arr4 = np.stack((a, b), axis = 0)
print(f"배열:\n {arr4} \nshape:\n {arr4.shape}\n")

# 5. 아래의 1차원 배열을 2:3:3 비율(총 3개)로 분할하세요.
arr = np.arange(8)
arr5 = np.split(arr, [2, 5])
print(f"배열:\n {arr5} \n")

배열:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
shape:
 (2, 2, 3)

배열:
 [array([0, 1]), array([2, 3, 4]), array([5, 6, 7])] 



In [155]:
# 6. 아래 두 배열을 axis=0, axis=1로 각각 stack하여 두 경우의 결과 shape을 모두 구하세요.
a = np.ones((2, 3))
b = np.zeros((2, 3))
arr6_1 = np.stack((a, b), axis = 0)
print(f"배열:\n {arr6_1} \nshape:\n {arr6_1.shape}\n")
arr6_2 = np.stack((a, b), axis = 1)
print(f"배열:\n {arr6_2} \nshape:\n {arr6_2.shape}\n")

배열:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]]] 
shape:
 (2, 2, 3)

배열:
 [[[1. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]]] 
shape:
 (2, 2, 3)



### 3-3. 배열의 정렬

In [163]:
# np.sort(array): 정렬된 복사본 반환
# array.sort(): 원본 배열을 정렬

# 1차원 배열
a = np.array([3, 1, 4, 2])
print(a, "\n")

# 정렬한 배열을 반환
s = np.sort(a)
print(s, "\n")

# 원본 정렬
a.sort()
print(a, "\n")


[3 1 4 2] 

[1 2 3 4] 

[1 2 3 4] 



In [158]:
# 2차원 배열 정렬
a = [[6, 5, 4], [3, 1, 2]]
s1 = np.sort(a, axis = 0)
print(s1, "\n")
s2 = np.sort(a, axis = 1)
print(s2, "\n")


[[3 1 2]
 [6 5 4]] 

[[4 5 6]
 [1 2 3]] 



In [160]:
# np.argsort(): 정렬 인덱스를 반환
a = np.array([3, 5, 1, 2, 4])
idx = np.argsort(a)
print(idx, "\n")
print(a[idx], "\n")

[2 3 0 4 1] 

[1 2 3 4 5] 



In [ ]:
# 실습3

# 1. 아래의 1차원 배열을 오름차순과 내림차순으로 각각 정렬하는 코드를 작성하세요.
arr1 = np.array([7, 2, 9, 4, 5])
arr1_1 = np.sort(arr1)
print(f"배열:\n{arr1_1}\n")
arr1_2 = np.sort(arr1)[::-1]
print(f"배열:\n{arr1_2}\n")

배열:
[2 4 5 7 9]

배열:
[9 7 5 4 2]



In [169]:
# 2. 아래의 2차원 배열에서 각 행(row) 별로 오름차순 정렬된 배열을 구하세요.
arr = np.array([[9, 2, 5],
                [3, 8 ,1]])
arr2 = np.sort(arr)
print(f"배열:\n{arr2}\n")


배열:
[[2 5 9]
 [1 3 8]]



In [172]:
# 3. 아래의 1차원 배열에서 정렬 결과(오름차순)가 되는 인덱스 배열을 구하고,
# 그 인덱스를 이용해 원본 배열을 직접 재정렬하는 코드를 작성하세요.
arr = np.array([10, 3, 7, 1, 9])
arr3_1 = np.argsort(arr)
print(f"정렬 인덱스 배열:\n{arr3_1}\n")
arr3_2 = arr[arr3_1]
print(f"배열:\n{arr3_2}\n")

정렬 인덱스 배열:
[3 1 2 4 0]

배열:
[ 1  3  7  9 10]



In [173]:
# 4. 아래 2차원 배열을 열(column) 기준(axis=0)으로 오름차순 정렬된 배열을 구하세요.
arr = np.array([[4, 7, 2],
                [9, 1, 5],
                [6, 8, 3]])
arr4 = np.sort(arr, axis = 0)
print(f"배열:\n{arr4}\n")

배열:
[[4 1 2]
 [6 7 3]
 [9 8 5]]



In [188]:
# 문제1
arr = np.array([10, 4, 7, 1, 9, 2, 5, 8])
arr1 = arr[2:7]
arr1_1 = np.sort(arr1)
arr[2:7] = arr1_1
print(f"배열:\n{arr}\n")

배열:
[10  4  1  2  5  7  9  8]

