In [2]:
import torch

## 1. 발전소 출력 데이터 텐서 생성

- 5개 발전소의 24시간 출력 데이터를 무작위로 생성 (50~500MW 범위)
- shape: (5, 24)인 텐서 만들기
- 각 발전소별 평균 출력량 계산하기

In [3]:
Power_Plant = torch.rand(5, 24) * 450 + 50
print(f"5개의 발전소의 24시간 출력 데이터:\n {Power_Plant}")
print("")
print(f"각 발전소별 평균 출력량: {torch.mean(Power_Plant, dim = 1)}")


5개의 발전소의 24시간 출력 데이터:
 tensor([[322.1392, 193.2895, 160.8142, 432.3200, 246.7290, 120.4161, 475.8677,
          70.7396, 129.7236, 122.6706, 205.4129, 282.3116, 123.9687, 174.9060,
          83.6729, 194.8064, 354.5075, 406.5852, 118.1690, 400.5834,  84.3660,
          75.4515, 200.7039, 252.8862],
        [456.9144,  58.8342, 151.1538, 361.9516, 403.5492, 169.8328, 352.0533,
         259.7458, 145.5700, 460.2709, 478.9849, 372.9452, 473.7728, 479.9702,
         268.9011, 267.4612, 221.0419,  82.6408, 459.2783, 123.7956, 366.0650,
         425.6508, 189.3578,  62.7052],
        [206.0925, 263.0065,  71.7545, 283.3133, 390.8794, 356.4670, 241.9581,
         267.9410, 100.9683,  55.3615, 188.0728, 274.2929, 281.7732, 163.2865,
         258.3654,  59.6678, 216.3089, 213.5631, 247.3707, 387.7802, 156.0590,
          77.7251, 295.9656, 349.7802],
        [292.3215, 199.2155, 359.7624, 192.8000, 124.1312, 492.0024, 144.7635,
          98.7932, 398.7692, 301.3621, 298.3733, 221.6223, 160.1119

## 2. 계절별 전력 수요 분석
- 봄/여름/가을/겨울 각 계절의 일별 전력 수요 데이터 (각 90일치)
- 4개 계절 데이터를 하나의 텐서로 합치기
- 계절별 최대 수요, 최소 수요 찾기
- 전체 데이터에서 상위 10% 수요값들만 필터링하기

In [4]:
# torch.rand(개수) * (최댓값 - 최솟값) + 최솟값
Spring = torch.rand(90) * 2001 + 3000
Summer = torch.rand(90) * 3001 + 5000
Fall = torch.rand(90) * 2001 + 3000
Winter = torch.rand(90) * 3001 + 4000

print(f"Spring 범위: {Spring.min():.1f} ~ {Spring.max():.1f}")
print(f"Summer 범위: {Summer.min():.1f} ~ {Summer.max():.1f}")
print(f"Fall 범위: {Fall.min():.1f} ~ {Fall.max():.1f}")
print(f"Winter 범위: {Winter.min():.1f} ~ {Winter.max():.1f}")

print("")

# 4개 계절 데이터를 하나의 텐서로 합치기
Season = torch.cat([Spring, Summer, Fall, Winter])

# 계절별 최대 수요, 최소 수요 찾기
print(f"봄 최대수요: {torch.max(Spring)}, 봄 최소수요: {torch.min(Spring)}")
print(f"여름 최대수요: {torch.max(Summer)}, 여름 최소수요: {torch.min(Summer)}")
print(f"가을 최대수요: {torch.max(Fall)}, 가을 최소수요: {torch.min(Fall)}")
print(f"겨울 최대수요: {torch.max(Winter)}, 겨울 최소수요: {torch.min(Winter)}")

print("")

# 전체 데이터에서 상위 10% 수요값들만 필터링하기
threshold = torch.quantile(Season, .9)
Season_filter = Season[Season >= threshold]
print(Season_filter)

print("")

print(f"상위 10% 기준값: {threshold:.1f}MW")
print(f"추출된 데이터 개수: {len(Season_filter)}개") 


Spring 범위: 3093.9 ~ 4940.1
Summer 범위: 5032.9 ~ 7970.2
Fall 범위: 3009.4 ~ 4959.0
Winter 범위: 4077.4 ~ 6981.6

봄 최대수요: 4940.07470703125, 봄 최소수요: 3093.9306640625
여름 최대수요: 7970.20068359375, 여름 최소수요: 5032.92431640625
가을 최대수요: 4958.99560546875, 가을 최소수요: 3009.37939453125
겨울 최대수요: 6981.64453125, 겨울 최소수요: 4077.387939453125

tensor([7900.6436, 7325.5459, 7133.0439, 7651.2817, 7291.3799, 7508.8672,
        7015.2959, 7348.8027, 7618.4629, 7721.0898, 7118.2280, 7054.8984,
        7058.9170, 7680.5088, 7182.5308, 7907.8594, 7890.9922, 7892.7734,
        7292.3477, 7970.2007, 7246.9854, 7715.8730, 7697.6709, 7833.3955,
        7586.4023, 7071.6865, 7113.0244, 6999.3960, 7042.4414, 7624.9185,
        7599.2139, 7736.8438, 7424.6533, 7487.7134, 7314.4614, 7784.2754])

상위 10% 기준값: 6983.4MW
추출된 데이터 개수: 36개


## 3. 배치 정규화 연습
- 10개 발전기의 효율 데이터 생성 (평균 85%, 표준편차 5%)
- 데이터를 평균 0, 표준편차 1로 정규화
- 다시 원래 스케일로 복원하기

In [5]:
# 표준정규분포 → 원하는 정규분포로 변환
# 데이터 = torch.randn(개수) * 표준편차 + 평균
Generator = torch.randn(10) * 0.05 + 0.85
print(Generator)
print(f"Generator 범위: {Generator.min():.1f} ~ {Generator.max():.1f}")

print("")

# 데이터를 평균 0, 표준편차 1로 정규화
Generator_data = (Generator - Generator.mean()) / Generator.std()
print(Generator_data)

print("")

# 다시 원래 스케일로 복원하기
Generator_main = Generator_data * Generator.std() + Generator.mean()
print(Generator_main)


tensor([0.8128, 0.7891, 0.8965, 0.8238, 0.8307, 0.8306, 0.8921, 0.9158, 0.8689,
        0.8220])
Generator 범위: 0.8 ~ 0.9

tensor([-0.8435, -1.4074,  1.1485, -0.5801, -0.4172, -0.4188,  1.0437,  1.6073,
         0.4911, -0.6236])

tensor([0.8128, 0.7891, 0.8965, 0.8238, 0.8307, 0.8306, 0.8921, 0.9158, 0.8689,
        0.8220])


## 4. ESS 충방전 시뮬레이션
- 100kWh 용량 ESS 모델링
- 24시간 동안의 충전(+)/방전(-) 스케줄 텐서 생성
- 시간별 SOC(State of Charge) 계산
- SOC가 20% 이하나 90% 이상이 되는 시점 찾기

In [19]:
# 100kWh 용량 ESS 모델링
ESS = torch.rand(24) * 60 - 30
print(f"ESS 범위: {ESS.min():.2f} ~ {ESS.max():.2f}")
print(f"평균 충방전량: {ESS.mean():.2f} kW")

print("")

# 시간별 SOC 계산
SOC = torch.cumsum(ESS, dim = 0) + 50
print(f"초기 SOC: 50kWh")
print(f"최종 SOC: {SOC[-1]:.2f}kWh")
print(f"SOC 범위: {SOC.min():.2f}kWh ~ {SOC.max():.2f}kWh")

# SOC가 20% 이하나 90% 이상이 되는 시점 찾기
ESS_capacity = 100
low_limit = ESS_capacity * 0.2
high_limit = ESS_capacity * 0.9
SOC_target = torch.where((SOC <= low_limit) | (SOC >= high_limit))

print(f"경고 발생 시간: {SOC_target[0].tolist()}h")

ESS 범위: -28.98 ~ 28.19
평균 충방전량: -5.45 kW

초기 SOC: 50kWh
최종 SOC: -80.88kWh
SOC 범위: -105.77kWh ~ 65.94kWh
경고 발생 시간: [3, 4, 9, 10, 17, 18, 19, 20, 21, 22, 23]h
