## PyTorch Quiz 1 : Tensor 초기화

In [1]:
import torch

### 1. 빈 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x4 크기의 Tensor
- 값이 초기화되지 않은 상태

In [2]:
# 여기에 코드를 작성합니다
x1 = torch.empty(3, 4)
print(x1)

tensor([[-1.2598e-01,  1.1631e-42,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


### 2. 0으로 채워진 Tensor 생성하기
다음과 같은 Tensor를 생성하세요.
- 2x5x3 크기의 Tensor
- 데이터 타입은 float64

In [7]:
# 여기에 코드를 작성합니다
x2 = torch.zeros(2, 5, 3, dtype = torch.float64)
print(x2)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)


### 3. 1로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 4x4 크기의 Tensor
- 데이터 타입은 int

In [8]:
# 여기에 코드를 작성합니다
x3 = torch.ones(4, 4, dtype = torch.int32)
print(x3)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


### 4. 랜덤 값으로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x3 크기의 Tensor
- 모든 값이 0과 1 사이의 랜덤 값

In [9]:
# 여기에 코드를 작성합니다
x4 = torch.rand(3, 3)
print(x4)

tensor([[0.5124, 0.2366, 0.3105],
        [0.6209, 0.0899, 0.8099],
        [0.8365, 0.0591, 0.3752]])


### 5. 다차원 Tensor 생성하기
다음과 같은 다차원 Tensor를 생성하세요.
- 값이 다음과 같은 2x3의 2D 배열
    ```
    [[1, 2, 3],
     [4, 5, 6]]
    ```

In [14]:
# 여기에 코드를 작성합니다
x5 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x5)

tensor([[1, 2, 3],
        [4, 5, 6]])


### 6. Tensor의 값을 변경하기
1. 표준정규분포의 값을 랜덤으로 갖는 2x2 Tensor를 생성하세요.
2. 생성된 Tensor의 속성을 물려받은 원소가 0인 새로운 텐서를 만들어보세요. 

In [16]:
# 여기에 코드를 작성합니다
x6 = torch.randn(2, 2)
x7 = x6.new_zeros(2, 2)
print(x7)

tensor([[0., 0.],
        [0., 0.]])
