## PyTorch Quiz 2 : 연산

In [2]:
import torch

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [4]:
# 여기에 코드를 작성합니다
x = torch.tensor([2, 4, 6])

x1 = x + 5
print(x1)

x2 = x1 - 3
print(x2)

tensor([ 7,  9, 11])
tensor([4, 6, 8])


### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [7]:
# 여기에 코드를 작성합니다
y1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y2 = torch.tensor([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print(f"더하기:\n {y1 + y2}")
print(f"빼기:\n {y1 - y2}")
print(f"곱하기:\n {y1 * y2}")
print(f"나누기:\n {y1 / y2}")

더하기:
 tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])
빼기:
 tensor([[-8, -6, -4],
        [-2,  0,  2],
        [ 4,  6,  8]])
곱하기:
 tensor([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]])
나누기:
 tensor([[0.1111, 0.2500, 0.4286],
        [0.6667, 1.0000, 1.5000],
        [2.3333, 4.0000, 9.0000]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [8]:
# 여기에 코드를 작성합니다
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
B = torch.tensor([[7, 8], [9, 10], [11, 12]])

print(f"내적의 곱:\n {torch.matmul(A, B)}")

내적의 곱:
 tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [12]:
# 여기에 코드를 작성합니다
R = torch.matmul(A, B)
R1 = R + 10

R2 = torch.clamp(R1, max = 100)
print(R2)

tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [14]:
# 여기에 코드를 작성합니다
M = torch.tensor([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])

print(f"각 열의 합계:\n {torch.sum(M, dim = 0)}")

각 열의 합계:
 tensor([55, 60, 65, 70, 75])
