### 3-1. 인덱싱, 슬라이싱
- numpy와 동일한 방식으로 인덱싱 슬라이싱 가능

In [1]:
import numpy as np
import torch

In [2]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(x[1, 1])
print(x[2, 0])
print(x[0, :])
print(x[:, 2])
print(x[[0, 1, 2], [0, 1, 2]]) # fancy indexing
print(x[x > 5]) # boolean indexing

tensor(5)
tensor(7)
tensor([1, 2, 3])
tensor([3, 6, 9])
tensor([1, 5, 9])
tensor([6, 7, 8, 9])


In [3]:
x = torch.tensor([10, 20, 30, 40, 50])

x[0] = 100
print(x)

tensor([100,  20,  30,  40,  50])


In [4]:
# 슬라이싱으로 값을 변경할 시 tensor로 값을 할당
x[1:4] = torch.tensor([200, 300, 400])
print(x)

tensor([100, 200, 300, 400,  50])


### 3-2. 텐서의 크기, 모양 변경
- torch.view()

In [7]:
x = torch.randn(4, 5)
print(x)

y = x.view(20)
print(y)

z = y.view(5, -1) # -1 >> 자동 계산
print(z)

n = z.view(2, 2, 5)
print(n)

tensor([[ 0.9273, -0.2820,  0.6769,  0.3918, -0.8479],
        [ 0.8990,  0.1944, -0.6554, -0.0027,  1.4277],
        [-0.8755, -0.1535, -1.1901, -0.5907,  0.2739],
        [-1.2740, -1.1159,  1.4533,  1.1914,  1.7822]])
tensor([ 0.9273, -0.2820,  0.6769,  0.3918, -0.8479,  0.8990,  0.1944, -0.6554,
        -0.0027,  1.4277, -0.8755, -0.1535, -1.1901, -0.5907,  0.2739, -1.2740,
        -1.1159,  1.4533,  1.1914,  1.7822])
tensor([[ 0.9273, -0.2820,  0.6769,  0.3918],
        [-0.8479,  0.8990,  0.1944, -0.6554],
        [-0.0027,  1.4277, -0.8755, -0.1535],
        [-1.1901, -0.5907,  0.2739, -1.2740],
        [-1.1159,  1.4533,  1.1914,  1.7822]])
tensor([[[ 0.9273, -0.2820,  0.6769,  0.3918, -0.8479],
         [ 0.8990,  0.1944, -0.6554, -0.0027,  1.4277]],

        [[-0.8755, -0.1535, -1.1901, -0.5907,  0.2739],
         [-1.2740, -1.1159,  1.4533,  1.1914,  1.7822]]])


### 3-3. 텐서의 숫자값 얻기
- tensor.item(): 스칼라 값 하나만 존재해야 사용 가능

In [9]:
x = torch.rand(2)
print(x)
print(x[0])

print(x[0].item())

tensor([0.0490, 0.2258])
tensor(0.0490)
0.048995256423950195


### 3-4. 차원 축소 및 증가

#### 차원 축소(제거)
- torch.squeeze(): 크기가 1인 차원을 제거 함.

In [15]:
t = torch.rand(3, 1, 3)
print(t)
print(t.shape)

print("")

ts = torch.squeeze(t)
print(ts)
print(ts.shape)

tensor([[[0.4272, 0.9118, 0.5167]],

        [[0.1330, 0.2577, 0.6776]],

        [[0.2243, 0.2392, 0.2353]]])
torch.Size([3, 1, 3])

tensor([[0.4272, 0.9118, 0.5167],
        [0.1330, 0.2577, 0.6776],
        [0.2243, 0.2392, 0.2353]])
torch.Size([3, 3])


#### 차원 증가(생성)
- torch.unsqueeze(): dim 설정에 따라 차원을 증가시킴
    - dim은 하나의 차원이 추가되는 인덱스

In [18]:
t = torch.rand(3, 3, 3)
print(t.shape)

# 0  가장 상위 차원 >> 3 가장 하위 차원 
ts1 = torch.unsqueeze(t, dim = 0)
print(ts1.shape)

ts2 = torch.unsqueeze(t, dim = 1)
print(ts2.shape)

ts3 = torch.unsqueeze(t, dim = 2)
print(ts3.shape)

ts4 = torch.unsqueeze(t, dim = 3)
print(ts4.shape)

torch.Size([3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([3, 1, 3, 3])
torch.Size([3, 3, 1, 3])
torch.Size([3, 3, 3, 1])


### 3-5. 텐서간 결합
- torch.stack(): 동일한 형식의 텐서를 새롭게 그룹화 함 >> 새로운 차원 생성됨

In [25]:
x = torch.tensor([1, 4])
y = torch.tensor([2, 5])
z = torch.tensor([3, 6])
result1 = torch.stack([x, y, z])
print(result1)

print("")

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
result2 = torch.stack([a, b])
print(result2)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


- torch.cat(): 데이터를 하나의 텐서로 병합 >> 새로운 차원 생성 X

In [20]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[7, 8], [9, 10]])

result3 = torch.cat((a, b), dim = 1)
print(result3)

tensor([[ 1,  2,  7,  8],
        [ 3,  4,  9, 10]])


### 3-6. 텐서 나누기
- torch.chunk(): 텐서를 지정한 개수에 따라 나눔
    - 나누어 떨어지지 않는 경우 >> 마지막 모각의 크기가 달라짐
    
- torch.split(): 지정한 사이즈에 따라 나눔
    - 나누어 떨어지지 않는 경우 >> 마지막 모각의 크기가 달라짐

In [21]:
t = torch.rand(3, 7)
print(t)

t1, t2, t3 = torch.chunk(t, 3, dim = 1)
print(t1)
print(t2)
print(t3)

tensor([[0.4456, 0.0918, 0.6990, 0.1407, 0.1763, 0.9340, 0.9551],
        [0.6069, 0.1413, 0.3946, 0.0996, 0.6650, 0.6535, 0.0491],
        [0.7983, 0.3443, 0.0381, 0.5628, 0.1626, 0.6887, 0.8666]])
tensor([[0.4456, 0.0918, 0.6990],
        [0.6069, 0.1413, 0.3946],
        [0.7983, 0.3443, 0.0381]])
tensor([[0.1407, 0.1763, 0.9340],
        [0.0996, 0.6650, 0.6535],
        [0.5628, 0.1626, 0.6887]])
tensor([[0.9551],
        [0.0491],
        [0.8666]])


In [23]:
t = torch.rand(3, 7)
print(t)

# 쪼갤 열의 개수 지정
t1, t2, t3 = torch.split(t, [2, 3, 2], dim = 1)
print(t1)
print(t2)
print(t3)

tensor([[0.2944, 0.5997, 0.5352, 0.7184, 0.2334, 0.9494, 0.8038],
        [0.3170, 0.9610, 0.2379, 0.8715, 0.5931, 0.1920, 0.7627],
        [0.3050, 0.7715, 0.7337, 0.8808, 0.7455, 0.2935, 0.7267]])
tensor([[0.2944, 0.5997],
        [0.3170, 0.9610],
        [0.3050, 0.7715]])
tensor([[0.5352, 0.7184, 0.2334],
        [0.2379, 0.8715, 0.5931],
        [0.7337, 0.8808, 0.7455]])
tensor([[0.9494, 0.8038],
        [0.1920, 0.7627],
        [0.2935, 0.7267]])
