In [1]:
import torch
print("setting complete.")

setting complete.


### 문제1
- 2차원 텐서 [[1, 2, 3], [4, 5, 6]]를 3x2 텐서로 변환해서 출력하세요.

In [3]:
# 여기에 코드를 작성합니다
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

X1 = X.view(3, 2)
print(X1)
print(X1.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


### 문제2
- 단일 값 텐서 tensor(42)에서 값을 추출하고 데이터 타입을 확인해서 출력하세요.

In [10]:
# 여기에 코드를 작성합니다
X2 = torch.tensor(42)
print(X2)

# (1) 값을 추출하고
X2_value = X2.item()
print(f"추출된 값: {X2_value}")

# (2) 데이터 타입을 확인하세요.
print(f"데이터 타입: {type(X2_value)}")
print(f"tensor 내부 타입: {X2.dtype}")


tensor(42)
추출된 값: 42
데이터 타입: <class 'int'>
tensor 내부 타입: torch.int64


### 문제 3
- 3차원 텐서 [[[1, 2, 3]]]에서 크기가 1인 차원을 제거해서 출력하세요.

In [13]:
# 여기에 코드를 작성합니다
X = torch.tensor([[[1, 2, 3]]])
X3 = torch.squeeze(X)
print(X3)
print(X3.shape)


tensor([1, 2, 3])
torch.Size([3])


### 문제 4
- 1차원 텐서 [1, 2, 3]에 새로운 차원을 추가하여 2차원 텐서로 만들어 출력하세요.

In [56]:
# 여기에 코드를 작성합니다
X = torch.tensor([1, 2, 3])
X4 = torch.unsqueeze(X, dim = 0)
print(X4)
print(X4.shape)

tensor([[1, 2, 3]])
torch.Size([1, 3])


### 문제 5
- 두 텐서 a = [1, 2]와 b = [3, 4]를 쌓아 2x2 텐서를 생성해서 출력하세요.


In [19]:
# 여기에 코드를 작성합니다
X = torch.tensor([1, 2])
Y = torch.tensor([3, 4])
X5 = torch.stack([X, Y])

print(X5)
print(X5.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


### 문제 6
- 두 텐서 a = [[1, 2], [3, 4]]와 b = [[5, 6], [7, 8]]를 열 방향으로 연결해서 출력하세요.

In [26]:
# 여기에 코드를 작성합니다
X = torch.tensor([[1, 2], [3, 4]])
Y = torch.tensor([[5, 6], [7, 8]])

X6 = torch.cat([X, Y], dim = 1)
print(X6)
print(X6.shape)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
torch.Size([2, 4])


### 문제 7
- 텐서 [[1, 2, 3], [4, 5, 6]]를 2개의 조각으로 나눠서 출력해보세요. (행 기준).

In [35]:
# 여기에 코드를 작성합니다
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

X7_1, X7_2 = torch.chunk(X, 2)
print(X7_1)
print(X7_2)

tensor([[1, 2, 3]])
tensor([[4, 5, 6]])


### 문제8
- 텐서 [1, 2, 3, 4, 5]를 각각 2, 2, 1의 크기로 나눠서 출력해보세요.

In [39]:
# 여기에 코드를 작성합니다
X = torch.tensor([1, 2, 3, 4, 5])

X8 = torch.split(X, [2, 2, 1])
print(X8)

(tensor([1, 2]), tensor([3, 4]), tensor([5]))


### 문제9
- 텐서 [[1, 2], [3, 4], [5, 6]]에서:
- dim=1 기준으로 크기 1씩 나누세요.
- 각각의 조각을 새로운 축에 쌓은 후 출력해보세요.

In [45]:
# 여기에 코드를 작성합니다
X = torch.tensor([[1, 2], 
                  [3, 4], 
                  [5, 6]])

# 1. 열 기준으로 크기 1씩 나누기
X9_1 = torch.split(X, 1, dim = 1)
print(X9_1)

# 2. 새로운 축에 쌓기
X9_2 = torch.stack(X9_1)
print(X9_2)


(tensor([[1],
        [3],
        [5]]), tensor([[2],
        [4],
        [6]]))
tensor([[[1],
         [3],
         [5]],

        [[2],
         [4],
         [6]]])


### 문제10
- 다음 텐서를 활용해서 아래 문제를 해결해보세요
  ```
  a = torch.tensor([[1, 2], [3, 4]])
  b = torch.tensor([[5, 6], [7, 8]])
  ```

1. 두 텐서를 열 기준으로 연결하고 결과를 출력하세요.
2. 연결된 텐서를 크기 `(4, 2)`로 변환하세요.
3. 변환된 텐서를 2개의 조각으로 나누고, 각 조각을 0번 축으로 스택하여 출력하세요.


In [65]:
# 여기에 코드를 작성합니다
a = torch.tensor([[1, 2], 
                  [3, 4]])
b = torch.tensor([[5, 6], 
                  [7, 8]])

# 1. 열 기준으로 병합
X10_1 = torch.cat((a, b), dim = 1)
print(X10_1)

# 2. 크기 (4, 2)로 변환
X10_2 = X10_1.view(4, 2)
print(X10_2)

# 3. 2개의 조각으로 나누고
X10_3 = torch.split(X10_2, 2)
print(X10_3)

# 4. 0번 축으로 스택
X10_4 = torch.stack(X10_3)
print(X10_4)


tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
tensor([[1, 2],
        [5, 6],
        [3, 4],
        [7, 8]])
(tensor([[1, 2],
        [5, 6]]), tensor([[3, 4],
        [7, 8]]))
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
